/*
 * JS for acceptp generated by Exadel Tiggzi
 *
 * Created on: Saturday, October 06, 2012, 11:31:47 AM (PDT)
 */
/************************************
 * JS API provided by Exadel Tiggzi  *
 ************************************/
/* Setting project environment indicator */
Tiggr.env = "bundle";
Tiggr.getProjectGUID = function() {
    return '44cece61-1495-4a3f-8b49-14001fd5dd25';
}
Tiggr.getTargetPlatform = function() {
    return '0';
}

function navigateTo(outcome, useAjax) {
    Tiggr.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Tiggr.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Tiggr.adjustContentHeightWithPadding();
}

function setDetailContent(pageUrl) {
    Tiggr.setDetailContent(pageUrl);
}
/**********************
 * SECURITY CONTEXTS  *
 **********************/
/*******************************
 *      SERVICE SETTINGS        *
 ********************************/
/*************************
 *      SERVICES          *
 *************************/
createSpinner("files/resources/lib/jquerymobile/images/ajax-loader.gif");
Tiggr.AppPages = [{
    "name": "homescreen",
    "location": "homescreen.html"
}, {
    "name": "enterscreen",
    "location": "enterscreen.html"
}, {
    "name": "acceptp",
    "location": "acceptp.html"
}];
j_30_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobileimage3': 'j_34',
        'mobilelabel5': 'j_35',
        'mobiletextarea6': 'j_36',
        'mobilebutton3': 'j_37'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    Tiggr.CurrentScreen = 'j_30';
    /*************************
     * NONVISUAL COMPONENTS  *
     *************************/
    var datasources = [];
    /************************
     * EVENTS AND HANDLERS  *
     ************************/
    j_30_beforeshow = function() {
        Tiggr.CurrentScreen = 'j_30';
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }
    // screen onload
    screen_7517_onLoad = j_30_onLoad = function() {
        screen_7517_elementsExtraJS();
        j_30_windowEvents();
        screen_7517_elementsEvents();
    }
    // screen window events
    screen_7517_windowEvents = j_30_windowEvents = function() {
        $('#j_30').bind('pageshow orientationchange', function() {
            adjustContentHeightWithPadding();
        });
    }
    // screen elements extra js
    screen_7517_elementsExtraJS = j_30_elementsExtraJS = function() {
        // screen (screen-7517) extra code
    }
    // screen elements handler
    screen_7517_elementsEvents = j_30_elementsEvents = function() {
        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });
        $('#j_33 [name="mobilebutton3"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Tiggr.navigateTo('homescreen', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        });
    }
    $("#j_30").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        j_30_beforeshow();
    });
    if (runBeforeShow) {
        j_30_beforeshow();
    } else {
        j_30_onLoad();
    }
}
$("#j_30").die("pageinit").live("pageinit", function(event, ui) {
    j_30_js();
});