/*
 * JS for acceptp generated by Exadel Tiggzi
 *
 * Created on: Saturday, October 06, 2012, 01:35:07 PM (PDT)
 */
/************************************
 * JS API provided by Exadel Tiggzi  *
 ************************************/
/* Setting project environment indicator */
Tiggr.env = "bundle";
Tiggr.getProjectGUID = function() {
    return '44cece61-1495-4a3f-8b49-14001fd5dd25';
}
Tiggr.getTargetPlatform = function() {
    return '0';
}

function navigateTo(outcome, useAjax) {
    Tiggr.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Tiggr.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Tiggr.adjustContentHeightWithPadding();
}

function setDetailContent(pageUrl) {
    Tiggr.setDetailContent(pageUrl);
}
/**********************
 * SECURITY CONTEXTS  *
 **********************/
/*******************************
 *      SERVICE SETTINGS        *
 ********************************/
/*************************
 *      SERVICES          *
 *************************/
createSpinner("files/resources/lib/jquerymobile/images/ajax-loader.gif");
Tiggr.AppPages = [{
    "name": "homescreen",
    "location": "homescreen.html"
}, {
    "name": "enterscreen",
    "location": "enterscreen.html"
}, {
    "name": "acceptp",
    "location": "acceptp.html"
}];
j_39_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilegrid1': 'j_43',
        'mobilegridcell1': 'j_44',
        'mobileimage3': 'j_45',
        'mobilegridcell2': 'j_46',
        'mobilelink1': 'j_47',
        'mobilespacer2': 'j_48',
        'mobilelabel5': 'j_49',
        'mobilebutton3': 'j_50'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    Tiggr.CurrentScreen = 'j_39';
    /*************************
     * NONVISUAL COMPONENTS  *
     *************************/
    var datasources = [];
    /************************
     * EVENTS AND HANDLERS  *
     ************************/
    j_39_beforeshow = function() {
        Tiggr.CurrentScreen = 'j_39';
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }
    // screen onload
    screen_7517_onLoad = j_39_onLoad = function() {
        screen_7517_elementsExtraJS();
        j_39_windowEvents();
        screen_7517_elementsEvents();
    }
    // screen window events
    screen_7517_windowEvents = j_39_windowEvents = function() {
        $('#j_39').bind('pageshow orientationchange', function() {
            adjustContentHeightWithPadding();
        });
    }
    // screen elements extra js
    screen_7517_elementsExtraJS = j_39_elementsExtraJS = function() {
        // screen (screen-7517) extra code
    }
    // screen elements handler
    screen_7517_elementsEvents = j_39_elementsEvents = function() {
        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });
        $('#j_42 [name="mobilebutton3"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Tiggr.navigateTo('homescreen', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        });
    }
    $("#j_39").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        j_39_beforeshow();
    });
    if (runBeforeShow) {
        j_39_beforeshow();
    } else {
        j_39_onLoad();
    }
}
$("#j_39").die("pageinit").live("pageinit", function(event, ui) {
    j_39_js();
});