/*
 * JS for enterscreen generated by Exadel Tiggzi
 *
 * Created on: Saturday, October 06, 2012, 12:51:17 PM (PDT)
 */
/************************************
 * JS API provided by Exadel Tiggzi  *
 ************************************/
/* Setting project environment indicator */
Tiggr.env = "bundle";
Tiggr.getProjectGUID = function() {
    return '44cece61-1495-4a3f-8b49-14001fd5dd25';
}
Tiggr.getTargetPlatform = function() {
    return '0';
}

function navigateTo(outcome, useAjax) {
    Tiggr.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Tiggr.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Tiggr.adjustContentHeightWithPadding();
}

function setDetailContent(pageUrl) {
    Tiggr.setDetailContent(pageUrl);
}
/**********************
 * SECURITY CONTEXTS  *
 **********************/
/*******************************
 *      SERVICE SETTINGS        *
 ********************************/
/*************************
 *      SERVICES          *
 *************************/
createSpinner("files/resources/lib/jquerymobile/images/ajax-loader.gif");
Tiggr.AppPages = [{
    "name": "homescreen",
    "location": "homescreen.html"
}, {
    "name": "enterscreen",
    "location": "enterscreen.html"
}, {
    "name": "acceptp",
    "location": "acceptp.html"
}];
j_12_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel11': 'j_16',
        'mobiletextinput2': 'j_17',
        'mobilegrid4': 'j_18',
        'mobilegridcell7': 'j_19',
        'mobilelabel2': 'j_20',
        'mobilegridcell8': 'j_21',
        'mobilelabel3': 'j_22',
        'mobilegrid5': 'j_23',
        'mobilegridcell9': 'j_24',
        'mobileselectmenu1': 'j_25',
        'selectmenuitem1': 'j_26',
        'mobilegridcell10': 'j_27',
        'mobiledatepicker1': 'j_28',
        'mobilelabel13': 'j_29',
        'mobiletextinput6': 'j_30',
        'mobilespacer3': 'j_31',
        'mobilebutton2': 'j_32'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    Tiggr.CurrentScreen = 'j_12';
    /*************************
     * NONVISUAL COMPONENTS  *
     *************************/
    var datasources = [];
    /************************
     * EVENTS AND HANDLERS  *
     ************************/
    j_12_beforeshow = function() {
        Tiggr.CurrentScreen = 'j_12';
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }
    // screen onload
    screen_538B_onLoad = j_12_onLoad = function() {
        screen_538B_elementsExtraJS();
        j_12_windowEvents();
        screen_538B_elementsEvents();
    }
    // screen window events
    screen_538B_windowEvents = j_12_windowEvents = function() {
        $('#j_12').bind('pageshow orientationchange', function() {
            adjustContentHeightWithPadding();
        });
    }
    // screen elements extra js
    screen_538B_elementsExtraJS = j_12_elementsExtraJS = function() {
        // screen (screen-538B) extra code
        $("#j_25").parent().find("a.ui-btn").attr("tabindex", "7");
        //DatePicker component JS
        mobiledatepicker1_selector = "#j_28";
        mobiledatepicker1_dataPickerOptions = {
            dateFormat: "mm/dd/yy",
            firstDay: 0,
            dayNamesMin: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
            monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
            showOtherMonths: true
        };
        mobiledatepicker1_dataPickerOptions.defaultDate = $.datepicker.formatDate(mobiledatepicker1_dataPickerOptions.dateFormat, new Date("2012/10/06"));
        Tiggr.__registerComponent('mobiledatepicker1', new Tiggr.TiggrMobileDatePickerComponent("j_28", mobiledatepicker1_dataPickerOptions));
    }
    // screen elements handler
    screen_538B_elementsEvents = j_12_elementsEvents = function() {
        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });
        $('#j_15 [name="mobilebutton2"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Tiggr.navigateTo('homescreen', {
                        reverse: false
                    });
                }
            },
        });
    }
    $("#j_12").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        j_12_beforeshow();
    });
    if (runBeforeShow) {
        j_12_beforeshow();
    } else {
        j_12_onLoad();
    }
}
$("#j_12").die("pageinit").live("pageinit", function(event, ui) {
    j_12_js();
});