/*
 * JS for homescreen generated by Exadel Tiggzi
 *
 * Created on: Saturday, October 06, 2012, 01:35:07 PM (PDT)
 */
/************************************
 * JS API provided by Exadel Tiggzi  *
 ************************************/
/* Setting project environment indicator */
Tiggr.env = "bundle";
Tiggr.getProjectGUID = function() {
    return '44cece61-1495-4a3f-8b49-14001fd5dd25';
}
Tiggr.getTargetPlatform = function() {
    return '0';
}

function navigateTo(outcome, useAjax) {
    Tiggr.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Tiggr.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Tiggr.adjustContentHeightWithPadding();
}

function setDetailContent(pageUrl) {
    Tiggr.setDetailContent(pageUrl);
}
/**********************
 * SECURITY CONTEXTS  *
 **********************/
/*******************************
 *      SERVICE SETTINGS        *
 ********************************/
/*************************
 *      SERVICES          *
 *************************/
createSpinner("files/resources/lib/jquerymobile/images/ajax-loader.gif");
Tiggr.AppPages = [{
    "name": "homescreen",
    "location": "homescreen.html"
}, {
    "name": "enterscreen",
    "location": "enterscreen.html"
}, {
    "name": "acceptp",
    "location": "acceptp.html"
}];
j_0_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton1': 'j_4',
        'mobilespacer1': 'j_5',
        'mobilelist1': 'j_6',
        'mobilelistitem1': 'j_7',
        'mobilelistitem2': 'j_8',
        'mobilelistitem3': 'j_9'
    };
    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }
    Tiggr.CurrentScreen = 'j_0';
    /*************************
     * NONVISUAL COMPONENTS  *
     *************************/
    var datasources = [];
    /************************
     * EVENTS AND HANDLERS  *
     ************************/
    j_0_beforeshow = function() {
        Tiggr.CurrentScreen = 'j_0';
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }
    // screen onload
    screen_43A2_onLoad = j_0_onLoad = function() {
        screen_43A2_elementsExtraJS();
        j_0_windowEvents();
        screen_43A2_elementsEvents();
    }
    // screen window events
    screen_43A2_windowEvents = j_0_windowEvents = function() {
        $('#j_0').bind('pageshow orientationchange', function() {
            adjustContentHeightWithPadding();
        });
    }
    // screen elements extra js
    screen_43A2_elementsExtraJS = j_0_elementsExtraJS = function() {
        // screen (screen-43A2) extra code
        listView = $("#j_6");
        theme = listView.attr("data-theme");
        if (typeof theme !== 'undefined') {
            var themeClass = "ui-btn-up-" + theme;
            listItem = $("#j_6 .ui-li-static");
            $.each(listItem, function(index, value) {
                $(this).addClass(themeClass);
            });
        }
    }
    // screen elements handler
    screen_43A2_elementsEvents = j_0_elementsEvents = function() {
        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });
        $('#j_3 [name="mobilebutton1"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Tiggr.navigateTo('enterscreen', {
                        reverse: false
                    });
                    Tiggr.navigateTo('enterscreen', {
                        transition: 'slide',
                        reverse: false
                    });
                }
            },
        });
        $('#j_3 [name="mobilelist1"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    $(this).mobilelist1({
                        'mode': 'bool',
                        'prompt': 'Accept invite?',
                        'useModal': true,
                        'buttons': {
                            'OK': {
                                click: function() {
                                    $('#dialogoutput').text('OK');
                                }
                            },
                            'Cancel': {
                                click: function() {
                                    $('#dialogoutput').text('Cancel');
                                },
                                icon: "delete",
                                theme: "c"
                            }
                        }
                    });
                }
            },
        });
    }
    $("#j_0").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        j_0_beforeshow();
    });
    if (runBeforeShow) {
        j_0_beforeshow();
    } else {
        j_0_onLoad();
    }
}
$("#j_0").die("pageinit").live("pageinit", function(event, ui) {
    j_0_js();
});